version: '3'

services:
    app:
        container_name: "blog_app"
        build:
            context: ./dockerfiles/fpm
            dockerfile: Dockerfile
            args:
                UID: "${UID}"
                GID: "${GID}"
        volumes:
            - ./:/usr/src/app
        tty: true
        depends_on:
            - mysql
        networks:
            - app_network
        user:
            "${UID}:1000"
    mysql:
        container_name: "blog_db"
        image: mysql:latest
        volumes:
            - dbdata:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - app_network
        environment:
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            SERVICE_TAGS: "dev"
            SERVICE_NAME: "mysql"
        ports:
            - "3306:3306"
        expose:
            - "3306"
    nginx:
        container_name: "blog_nginx"
        image: nginx:latest
        networks:
            - app_network
        volumes:
            - ./dockerfiles/nginx/conf/:/etc/nginx/conf.d/
            - logs:/var/log/nginx
            - ./public/:/usr/src/app/public/
        ports:
            - "${APP_PORT}:80"
        links:
            - app
volumes:
    dbdata:
        driver: local
    logs:
        driver: local
networks:
    app_network:
        driver: bridge

